dist: trusty
language: node_js
node_js:
- '10'
- '8'
- '6'
env:
  matrix:
  - CONTINUOUS_INTEGRATION=1
  global:
    secure: gBIzQfN+ExBh+OXLEbDqqdQQZqhks6tdOTzYgW/UcH+NBxNR4eGLVKxJMGaZ5wB02awY1uTsZkweXIIAeHZ8y4JVQ+5Kcf6BSkkmYCNs9WGGun7d2IvhG2Oeez6hGdqzFKBGmWTpg/8oa2ZKBB+AEbjDxIYOX3MMf4t7WGJjPVc=
before_install:
- sudo add-apt-repository "deb http://tei.oucs.ox.ac.uk/teideb/binary ./"
- sudo apt-key add test/tei.key
- sudo apt-get update -qq
- sudo apt-get install -y xsltproc jing saxon
# We need at least npm 5
- '[[ $(npm -v) =~ ^[5-9].*$ ]] || npm install -g npm@latest'
- npm install -g greenkeeper-lockfile@1
script: gulp test
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
branches:
  except:
  - master
